# --- Development docker compose file

version: '3.8'

networks:
  dash_chatgpt-network-dev:

services:
  # database serving as cache for callbacks and broker for async. processes
  redis:
    container_name: dash_chatgpt_challenge-redis-dev
    image: docker.io/redis:latest
    networks:
      - dash_chatgpt-network-dev
    restart: unless-stopped

  # worker for async. processes
  celery_worker:
    container_name: propaganda_bot-celery_worker-dev
    image: docker.io/vsisl/propaganda_bot-celery_worker:latest
    build:
      context: .
      dockerfile: celery_app/Dockerfile
    networks:
      - dash_chatgpt-network-dev
    environment:
      - PYTHONUNBUFFERED=1                  # in order to get python prints into the container's log file
      - REDISTOGO_URL=redis://redis:6379    # to connect with redis
      - OPENAI_API_KEY=${OPENAI_API_KEY}    # add your api key here
    depends_on:
      - redis
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: '200k'
    restart: unless-stopped
    volumes:
      - ../dash-chatgpt-challenge:/home/docker/dash-chatgpt-challenge

  # plotly dash app
  dash_app:
    container_name: propaganda_bot-dash_app-dev
    image: docker.io/vsisl/propaganda_bot-dash_app:latest
    build:
      context: .
      dockerfile: dash_app/Dockerfile
    networks:
      - dash_chatgpt-network-dev
    ports:
      - "8000:8000"                         # specify the port for the webapp; host port:container port
    environment:
      - PYTHONUNBUFFERED=1                  # in order to get python prints into the container's log file
      - REDISTOGO_URL=redis://redis:6379    # to connect with redis
      - OPENAI_API_KEY=${OPENAI_API_KEY}    # add your api key here
    depends_on:
      - redis
      - celery_worker
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: '200k'
    restart: unless-stopped
    volumes:
      - ../dash-chatgpt-challenge:/home/docker/dash-chatgpt-challenge