"""Celery app for executing async. tasks generated by the dash app
"""

import os
from celery import Celery

redis_url = os.getenv(
    "REDISTOGO_URL", default="redis://localhost:6379"
)  # REDISTOGO_URL var from docker-compose file

celery_app = Celery(
    __name__,
    broker=redis_url + "/1",
    backend=redis_url + "/2",
    include=[
        "dash_app.pages.generate_propaganda",
        "dash_app.pages.analyze_propaganda",
    ],
)

celery_app.conf.update(
    result_expires=8 * 3600,  # keep results in DB for 8 hours
)
