#############################################################################################################################################################################################################################
# #!/usr/bin/env python3                                                                                                                                                                                                    #
# # -*- coding: utf-8 -*-                                                                                                                                                                                                   #
# """                                                                                                                                                                                                                       #
# Created on Tue Jul 11 10:23:25 2023                                                                                                                                                                                       #
#                                                                                                                                                                                                                           #
# @author: chrvt                                                                                                                                                                                                            #
# """                                                                                                                                                                                                                       #
#                                                                                                                                                                                                                           #
# import dash                                                                                                                                                                                                               #
# from dash import Input, Output, State, html, callback                                                                                                                                                                     #
# import dash_bootstrap_components as dbc                                                                                                                                                                                   #
# # chat-gpt API                                                                                                                                                                                                            #
# import openai                                                                                                                                                                                                             #
# import ast                                                                                                                                                                                                                #
# import re                                                                                                                                                                                                                 #
#                                                                                                                                                                                                                           #
# #########################################################################                                                                                                                                                 #
# # def split_text_into_sentences(text):                                  #                                                                                                                                                 #
# #     # Define the sentence delimiter pattern                           #                                                                                                                                                 #
# #     sentence_delimiter = r’(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s’ #                                                                                                                                                 #
# #     # Split the text into sentences using the delimiter pattern       #                                                                                                                                                 #
# #     sentences = re.split(sentence_delimiter, text)                    #                                                                                                                                                 #
# #     return sentences                                                  #                                                                                                                                                 #
# #########################################################################                                                                                                                                                 #
#                                                                                                                                                                                                                           #
# def concatenate_sentences(sentences):                                                                                                                                                                                     #
#     text = ' '.join(sentences)                                                                                                                                                                                            #
#     return text                                                                                                                                                                                                           #
#                                                                                                                                                                                                                           #
#                                                                                                                                                                                                                           #
#     #as for now, we can use the API key of a friend but we should get our own eventually                                                                                                                                  #
# openai.api_key  =                                                                                                                                                                                                         #
# # creates chatGPT response                                                                                                                                                                                                #
# # input: prompt, output: response                                                                                                                                                                                         #
# def get_completion(prompt, model='gpt-3.5-turbo'):                                                                                                                                                                        #
#     messages = [{'role': user, 'content': prompt}]                                                                                                                                                                        #
#     response = openai.ChatCompletion.create(                                                                                                                                                                              #
#         model=model,                                                                                                                                                                                                      #
#         messages=messages,                                                                                                                                                                                                #
#         temperature=0, # this is the degree of randomness of the model’s output                                                                                                                                           #
#     )                                                                                                                                                                                                                     #
#     return response.choices[0].message['content']                                                                                                                                                                         #
# dash.register_page(__name__, path='/')                                                                                                                                                                                    #
# ### LAYOUTS                                                                                                                                                                                                               #
# # column - text input                                                                                                                                                                                                     #
# column_input = dbc.Col(                                                                                                                                                                                                   #
#     [                                                                                                                                                                                                                     #
#         dbc.Textarea(                                                                                                                                                                                                     #
#             id=“input-text_to_process”,                                                                                                                                                                                   #
#             placeholder=“Type or paste text here...“,                                                                                                                                                                     #
#             # type=“text”,      # can be used with dbc.Input                                                                                                                                                              #
#             size=“lg”,                                                                                                                                                                                                    #
#             minlength=50,                                                                                                                                                                                                 #
#             maxlength=5000,  # can be used to limit nr. of characters                                                                                                                                                     #
#         ),                                                                                                                                                                                                                #
#         dbc.Button(                                                                                                                                                                                                       #
#             id=“button-submit”,                                                                                                                                                                                           #
#             children=“Submit”,                                                                                                                                                                                            #
#         ),                                                                                                                                                                                                                #
#     ],                                                                                                                                                                                                                    #
#     width=6,                                                                                                                                                                                                              #
# )                                                                                                                                                                                                                         #
# # column - analysis results                                                                                                                                                                                               #
# column_output = dbc.Col(                                                                                                                                                                                                  #
#     [                                                                                                                                                                                                                     #
#         dbc.Container(                                                                                                                                                                                                    #
#             id=“container-analysis_results”,                                                                                                                                                                              #
#             children=“PLACEHOLDER: analysis results with appear here...“,                                                                                                                                                 #
#         )                                                                                                                                                                                                                 #
#     ],                                                                                                                                                                                                                    #
#     width=6,                                                                                                                                                                                                              #
# )                                                                                                                                                                                                                         #
# # page layout                                                                                                                                                                                                             #
# layout = dbc.Container(children=[dbc.Row([column_input, column_output])])                                                                                                                                                 #
# ### CALLBACKS                                                                                                                                                                                                             #
# @callback(                                                                                                                                                                                                                #
#     Output(component_id=“container-analysis_results”, component_property=“children”),                                                                                                                                     #
#     Input(component_id=“button-submit”, component_property=“n_clicks”),                                                                                                                                                   #
#     State(component_id=“input-text_to_process”, component_property=“value”),                                                                                                                                              #
#     prevent_initial_call=True,  # this prevents callback triggering at page load (before the Submit button is clicked)                                                                                                    #
# )                                                                                                                                                                                                                         #
# def process_text(n_clicks, input_text):                                                                                                                                                                                   #
#     “”"This is an example callback function.                                                                                                                                                                              #
#     Callback functions are used to dynamically populate the content of the app.                                                                                                                                           #
#     You can think of them as of the “backend” of the app.                                                                                                                                                                 #
#     Read more here: https://dash.plotly.com/basic-callbacks                                                                                                                                                               #
#     :param n_clicks: int                                                                                                                                                                                                  #
#     :param input_text: str                                                                                                                                                                                                #
#     :return: str                                                                                                                                                                                                          #
#     “”"                                                                                                                                                                                                                   #
#     # TODO: make some machine learning magic here                                                                                                                                                                         #
#     print(“callback fired...“)                                                                                                                                                                                            #
#     # create output - e.g. analysis results or modified input text                                                                                                                                                        #
#     #output_text = str(input_text).upper()                                                                                                                                                                                #
#     #  what do we want chatGPT to do?                                                                                                                                                                                     #
#     prompt = f”“”                                                                                                                                                                                                         #
#        Write the text delimited by triple backticks \                                                                                                                                                                     #
#        in form of a russian propaganda breaking news.                                                                                                                                                                     #
#       ```{input_text}```                                                                                                                                                                                                  #
#       “”                                                                                                                                                                                                                  #
#                                                                                                                                                                                                                           #
#     print(’Input prompt: ’, input_text)                                                                                                                                                                                   #
#     print(’\n ---------’)                                                                                                                                                                                                 #
#     # Step 1: generate propaganda                                                                                                                                                                                         #
#     propaganda_text = get_completion(prompt)                                                                                                                                                                              #
#     print(’Propaganda text: ’, propaganda_text)                                                                                                                                                                           #
#     # Step 2: Classify each sentence into propaganda classes                                                                                                                                                              #
#     array_of_setences = split_text_into_sentences(propaganda_text)                                                                                                                                                        #
#     #Just give me a one-hot encoded vector with only numerical values as an answer. Enclose the vector in brackets and seperate each number with a comma. Don’t add any addtional text or an explaination of the classes. #
#     #import pdb; pdb.set_trace()                                                                                                                                                                                          #
#     result = []                                                                                                                                                                                                           #
#     for sentence in array_of_setences:                                                                                                                                                                                    #
#             prompt = f"""                                                                                                                                                                                                 #
#                      classify the sentence delimited by triple backticks into the following classes:                                                                                                                      #
#                      ‘Appeal to Authority’, ‘Appeal to Fear Prejudice’,‘Bandwagon, Reductio ad hitlerum’,' Black and White Fallacy’, \                                                                                    #
#                      ‘Causal Oversimplification’, ‘Doubt’, ‘Exaggeration, Minimisation’, ‘Flag-Waving’, ‘Loaded Languag’, \                                                                                               #
#                      ‘Name Calling, Labeling’, ‘Repetition’, ‘Slogans’, ‘Thought-terminating Cliches’, \                                                                                                                  #
#                      ‘Whataboutism, Straw Man, Red Herring’                                                                                                                                                               #
#                      Only give me an array of the classes which fit to the sentence. Just the description not the numbers. Seperate two classes with a comma.                                                             #
#                       ```{sentence}````                                                                                                                                                                                   #
#                      """                                                                                                                                                                                                  #
#             classes = get_completion(prompt)                                                                                                                                                                              #
#             #import pdb; pdb.set_trace()                                                                                                                                                                                  #
#             #classes = ast.literal_eval(classes_) # convert string to numerical array                                                                                                                                     #
#             #print(‘sentence classified ‘, classes)                                                                                                                                                                       #
#            # import pdb; pdb.set_trace()                                                                                                                                                                                  #
#             result.append((sentence, classes))                                                                                                                                                                            #
#             # result consists of all sentencens with their classification                                                                                                                                                 #
#     print(‘---------’)                                                                                                                                                                                                    #
#     print(‘Classificatio: ‘,result)                                                                                                                                                                                       #
#     print(‘---------‘)                                                                                                                                                                                                    #
#     # Step 3: Reformulate setence                                                                                                                                                                                         #
#     import pdb; pdb.set_trace()                                                                                                                                                                                           #
#     # loop throught the sentences                                                                                                                                                                                         #
#     reformulation = []                                                                                                                                                                                                    #
#     for k in range(len(array_of_setences)):                                                                                                                                                                               #
#         sentence, classes = result[k]  # get sentence and classes                                                                                                                                                         #
#         # write prompt                                                                                                                                                                                                    #
#         prompt = f”“”                                                                                                                                                                                                     #
#          Reformulate the setence delimited by triple backticks such that you would not classify the sentence as \                                                                                                         #
#          as one of the following classes:                                                                                                                                                                                 #
#          {classes}                                                                                                                                                                                                        #
#          If you think no reformulation is necessary, don’t change any reformulation but just give me the same sentence as output.                                                                                         #
#          Just give me the reformulated sentence as an output. No additional text or explaination needed.                                                                                                                  #
#          ```{sentence}```                                                                                                                                                                                                 #
#           “”"                                                                                                                                                                                                             #
#         #import pdb; pdb.set_trace()                                                                                                                                                                                      #
#         reformulation_k = get_completion(prompt)                                                                                                                                                                          #
#         reformulation.append(reformulation_k)                                                                                                                                                                             #
#     print(‘---------‘)                                                                                                                                                                                                    #
#     print(‘\n Reformulation: ’, concatenate_sentences(reformulation))                                                                                                                                                     #
#     return output_text                                                                                                                                                                                                    #
# # input tets                                                                                                                                                                                                              #
# #                                                                                                                                                                                                                         #
# # The glorious nation of Russia is proud to announce that all trees in America are flourishing and vibrant, thanks to the wise leadership of our esteemed President.                                                      #
# # Out satellite imagery has confirmed that every single tree in the country is a beautiful shade of green, a testament to the strength of resilience of the American people.                                              #
# # To do:                                                                                                                                                                                                                  #
# #   + show propaganda text first and then continue processing (takes time)                                                                                                                                                #
#############################################################################################################################################################################################################################
